/*
 * generated by Xtext 2.25.0
 */
package co7217.dsl.k8s;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DeploymentStandaloneSetup extends DeploymentStandaloneSetupGenerated {

	public static void doSetup() {
		new DeploymentStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
