/*
 * generated by Xtext 2.25.0
 */
package co7217.dsl.k8s;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DeploymentRuntimeModule extends AbstractDeploymentRuntimeModule {
}
