
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "dsl-example"
  namespace: "xyz"
  labels:
    app: "dsl-example"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "dsl-example"
  template:
    metadata:
      labels:
        app: "dsl-example"
    spec:
      containers:
      - name: "busybox"
        image: "gcr.io/google-containers/busybox:latest"
      - name: "defaultbackend"
        image: "gcr.io/google-containers/defaultbackend:latest"

---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "hpa"
  namespace: "xyz"
  labels:
    app: "dsl-example"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "dsl-example"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "service"
  namespace: "xyz"
  labels:
    app: "dsl-example"
spec:
  ports:
  - name: "busybox-expose"
    protocol: "TCP"
    port: 80
    targetPort: 80
  - name: "backend-expose"
    protocol: "TCP"
    port: 8080
    targetPort: 8080
  selector:
    app: "dsl-example"
  type: "LoadBalancer"
  LoadBalancerIP: "192.168.19.18"
