
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "another-example"
  namespace: "default"
  labels:
    alabel: "make-this-same-for-svc-and-dep"
    label2: "moreLabels"
spec:
  replicas: 9
  selector:
    matchLabels:
      alabel: "make-this-same-for-svc-and-dep"
  template:
    metadata:
      labels:
        alabel: "make-this-same-for-svc-and-dep"
    spec:
      containers:
      - name: "busybox"
        image: "gcr.io/google-containers/busybox:latest"

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "service"
  namespace: "default"
  labels:
    app: "dsl-example"
    label2: "randomLabel"
spec:
  ports:
  - name: "busybox-expose"
    protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    alabel: "make-this-same-for-svc-and-dep"
  type: "ClusterIP"
  ClusterIP: "192.168.19.18"
