/*
 * generated by Xtext 2.25.0
 */
package co7217.dsl.k8s.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link DeploymentWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractDeploymentWebModule extends DefaultWebModule {

}
