/**
 * generated by Xtext 2.25.0
 */
package co7217.dsl.k8s.deployment;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dep</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co7217.dsl.k8s.deployment.Dep#getReplicas <em>Replicas</em>}</li>
 *   <li>{@link co7217.dsl.k8s.deployment.Dep#getContainers <em>Containers</em>}</li>
 * </ul>
 *
 * @see co7217.dsl.k8s.deployment.DeploymentPackage#getDep()
 * @model
 * @generated
 */
public interface Dep extends Header
{
  /**
   * Returns the value of the '<em><b>Replicas</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Replicas</em>' attribute.
   * @see #setReplicas(int)
   * @see co7217.dsl.k8s.deployment.DeploymentPackage#getDep_Replicas()
   * @model
   * @generated
   */
  int getReplicas();

  /**
   * Sets the value of the '{@link co7217.dsl.k8s.deployment.Dep#getReplicas <em>Replicas</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Replicas</em>' attribute.
   * @see #getReplicas()
   * @generated
   */
  void setReplicas(int value);

  /**
   * Returns the value of the '<em><b>Containers</b></em>' containment reference list.
   * The list contents are of type {@link co7217.dsl.k8s.deployment.Container}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Containers</em>' containment reference list.
   * @see co7217.dsl.k8s.deployment.DeploymentPackage#getDep_Containers()
   * @model containment="true"
   * @generated
   */
  EList<Container> getContainers();

} // Dep
