/**
 * generated by Xtext 2.25.0
 */
package co7217.dsl.k8s.deployment;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hpa</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co7217.dsl.k8s.deployment.Hpa#getTarget <em>Target</em>}</li>
 *   <li>{@link co7217.dsl.k8s.deployment.Hpa#getMinimum <em>Minimum</em>}</li>
 *   <li>{@link co7217.dsl.k8s.deployment.Hpa#getMaximum <em>Maximum</em>}</li>
 *   <li>{@link co7217.dsl.k8s.deployment.Hpa#getMetrices <em>Metrices</em>}</li>
 * </ul>
 *
 * @see co7217.dsl.k8s.deployment.DeploymentPackage#getHpa()
 * @model
 * @generated
 */
public interface Hpa extends Header
{
  /**
   * Returns the value of the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' attribute.
   * @see #setTarget(String)
   * @see co7217.dsl.k8s.deployment.DeploymentPackage#getHpa_Target()
   * @model
   * @generated
   */
  String getTarget();

  /**
   * Sets the value of the '{@link co7217.dsl.k8s.deployment.Hpa#getTarget <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' attribute.
   * @see #getTarget()
   * @generated
   */
  void setTarget(String value);

  /**
   * Returns the value of the '<em><b>Minimum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Minimum</em>' attribute.
   * @see #setMinimum(int)
   * @see co7217.dsl.k8s.deployment.DeploymentPackage#getHpa_Minimum()
   * @model
   * @generated
   */
  int getMinimum();

  /**
   * Sets the value of the '{@link co7217.dsl.k8s.deployment.Hpa#getMinimum <em>Minimum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Minimum</em>' attribute.
   * @see #getMinimum()
   * @generated
   */
  void setMinimum(int value);

  /**
   * Returns the value of the '<em><b>Maximum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Maximum</em>' attribute.
   * @see #setMaximum(int)
   * @see co7217.dsl.k8s.deployment.DeploymentPackage#getHpa_Maximum()
   * @model
   * @generated
   */
  int getMaximum();

  /**
   * Sets the value of the '{@link co7217.dsl.k8s.deployment.Hpa#getMaximum <em>Maximum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Maximum</em>' attribute.
   * @see #getMaximum()
   * @generated
   */
  void setMaximum(int value);

  /**
   * Returns the value of the '<em><b>Metrices</b></em>' containment reference list.
   * The list contents are of type {@link co7217.dsl.k8s.deployment.Metrice}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metrices</em>' containment reference list.
   * @see co7217.dsl.k8s.deployment.DeploymentPackage#getHpa_Metrices()
   * @model containment="true"
   * @generated
   */
  EList<Metrice> getMetrices();

} // Hpa
