/**
 * generated by Xtext 2.25.0
 */
package co7217.dsl.k8s.deployment;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Port</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co7217.dsl.k8s.deployment.Port#getName <em>Name</em>}</li>
 *   <li>{@link co7217.dsl.k8s.deployment.Port#getProtocol <em>Protocol</em>}</li>
 *   <li>{@link co7217.dsl.k8s.deployment.Port#getInport <em>Inport</em>}</li>
 *   <li>{@link co7217.dsl.k8s.deployment.Port#getTargetport <em>Targetport</em>}</li>
 * </ul>
 *
 * @see co7217.dsl.k8s.deployment.DeploymentPackage#getPort()
 * @model
 * @generated
 */
public interface Port extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see co7217.dsl.k8s.deployment.DeploymentPackage#getPort_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link co7217.dsl.k8s.deployment.Port#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Protocol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Protocol</em>' attribute.
   * @see #setProtocol(String)
   * @see co7217.dsl.k8s.deployment.DeploymentPackage#getPort_Protocol()
   * @model
   * @generated
   */
  String getProtocol();

  /**
   * Sets the value of the '{@link co7217.dsl.k8s.deployment.Port#getProtocol <em>Protocol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Protocol</em>' attribute.
   * @see #getProtocol()
   * @generated
   */
  void setProtocol(String value);

  /**
   * Returns the value of the '<em><b>Inport</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inport</em>' attribute.
   * @see #setInport(int)
   * @see co7217.dsl.k8s.deployment.DeploymentPackage#getPort_Inport()
   * @model
   * @generated
   */
  int getInport();

  /**
   * Sets the value of the '{@link co7217.dsl.k8s.deployment.Port#getInport <em>Inport</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inport</em>' attribute.
   * @see #getInport()
   * @generated
   */
  void setInport(int value);

  /**
   * Returns the value of the '<em><b>Targetport</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Targetport</em>' attribute.
   * @see #setTargetport(int)
   * @see co7217.dsl.k8s.deployment.DeploymentPackage#getPort_Targetport()
   * @model
   * @generated
   */
  int getTargetport();

  /**
   * Sets the value of the '{@link co7217.dsl.k8s.deployment.Port#getTargetport <em>Targetport</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Targetport</em>' attribute.
   * @see #getTargetport()
   * @generated
   */
  void setTargetport(int value);

} // Port
