/*
 * generated by Xtext 2.25.0
 */
package co7217.dsl.k8s.parser.antlr;

import co7217.dsl.k8s.parser.antlr.internal.InternalDeploymentParser;
import co7217.dsl.k8s.services.DeploymentGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DeploymentParser extends AbstractAntlrParser {

	@Inject
	private DeploymentGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDeploymentParser createParser(XtextTokenStream stream) {
		return new InternalDeploymentParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public DeploymentGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DeploymentGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
