/*
 * generated by Xtext 2.25.0
 */
package co7217.dsl.k8s.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DeploymentAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("co7217/dsl/k8s/parser/antlr/internal/InternalDeployment.tokens");
	}
}
