/*
 * generated by Xtext 2.25.0
 */
package co7217.dsl.k8s.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDeploymentScopeProvider extends DelegatingScopeProvider {
}
