/*
 * generated by Xtext 2.25.0
 */
package co7217.dsl.k8s.web;

import co7217.dsl.k8s.DeploymentRuntimeModule;
import co7217.dsl.k8s.DeploymentStandaloneSetup;
import co7217.dsl.k8s.ide.DeploymentIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class DeploymentWebSetup extends DeploymentStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DeploymentRuntimeModule(), new DeploymentIdeModule(), new DeploymentWebModule()));
	}
	
}
