/*
 * generated by Xtext 2.25.0
 */
package co7217.dsl.k8s.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class DeploymentWebModule extends AbstractDeploymentWebModule {
}
